### ISSUE TITLE
kotaku.com

### ISSUE THREAD

**Issue by phynias** [smokingwheels/smokingwheels.github.io#3]
not sure why kotaku.com is on your list. it's a legit gaming site.

**Comment by smokingwheels** [comment]
Does not seem to be anything there righ now got the  "Apache2 Ubuntu Default Page"

**Comment by Nivl** [comment]
Weird, [Kotaku exists since 2004](https://en.wikipedia.org/wiki/Kotaku). Maybe it's region restricted? I also think it should not be part of the blacklist.

**Comment by smokingwheels** [comment]
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts its on this list
