### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by popeofnope** [smokingwheels/smokingwheels.github.io#7]
Hi -

You have a few false positives in your /allhosts file - this is primarily because it's a bit out of date. It looks like this may have been pulled from another list which has since been updated to remove these FPs when we discovered them. The domain "rally.io" is no longer owned by a spammer/malware spreader, it's owned by a legit company who creates extensions for Twitch.tv. 

Please see: https://www.rally.io - if needed you can reach me using security@rally.io there.

With that, please remove the following domains from /allhosts:

my.rally.io
rally.io
www.rally.io

Thanks!

**Comment by thebozzcl** [comment]
To add to the list:

ipv6.he.net
he.net

This is a legit ISP.

**Comment by smokingwheels** [comment]
I have no control over https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
